/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:910a9c72-ca85-4628-9633-f5b4dd7b8302",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rTKDquQDV",
    "aws_user_pools_web_client_id": "lftc52ap6ssplv5h8imjdutd8",
    "oauth": {}
};


export default awsmobile;
